FROM azul/zulu-openjdk:17-jre-latest

ENV TZ=Asia/Seoul

RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app

COPY ./customer-api/build/libs/*.jar app.jar

RUN chown appuser:appuser app.jar

USER appuser

ENTRYPOINT ["java", \
    "-XX:InitialRAMPercentage=25.0", \
    "-XX:MaxRAMPercentage=80.0", \
    "-Dspring.profiles.active=prod", \
    "-jar", \
    "app.jar"]
